:: This was generated by chatgpt as I use linux
:: use at your own risk
:: Feel free to submit a PR for a better script

@echo off
setlocal

:: Check if t4 is installed
where t4 >nul 2>nul
if %errorlevel% neq 0 (
    set /p installit="t4 was not found. Would you like to install it? (Y/n) "
    if /i "%installit%"=="Y" (
        dotnet tool install -g dotnet-t4
        setx PATH "%PATH%;%USERPROFILE%\.dotnet\tools"
    ) else (
        exit /b 1
    )
)

:: Set SOLUTION_DIR to the script's directory
for %%I in ("%~dp0.") do set SOLUTION_DIR=%%~fI

:: Check if .env file exists
if exist ".env" (
    for /f "delims=" %%A in (.env) do set %%A
) else (
    set /p GAME_DIR="Enter Game Directory: "
    (
        echo @echo off
        echo set GAME_DIR=%GAME_DIR%
    ) > .env
)

:: Create PatchManager.cs
(
    echo namespace ArchipelagoClusterTruck.Patches;
    echo.
    echo public static class PatchManager {
    echo     public static void PatchAll(){}
    echo }
) > Patches\PatchManager.cs

echo First build pre code gen
dotnet build

echo Code Gen
t4 -r "%SOLUTION_DIR%\bin\Debug\net35\ArchipelagoClusterTruck.dll" ^
   -r "%SOLUTION_DIR%\bin\Debug\net35\Archipelago.MultiClient.Net.dll" ^
   -r "%GAME_DIR%\Clustertruck_Data\Managed\UnityEngine.dll" ^
   -r "%GAME_DIR%\BepInEx\core\BepInEx.dll" ^
   -r "%GAME_DIR%\Clustertruck_Data\Managed\Assembly-CSharp.dll" ^
   Patches\PatchManager.tt

echo Final Build
dotnet build %*

endlocal
